enablePinning = false
keepCentered = true
settingsButton = false
enableBook = true

[newRecipes]
unlockAll = true
enableBounce = false

[instantCraft]
showButton = false
enabled = false

[alternativeRecipes]
onHover = true
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = true
