version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
furniture = true
furnies = true
ends_delight = true
nightlights = true
farmersdelight = true
mcwfurnitures = true
woodwevegot = true
waystones = true
pfm = true
endrem = true
mynethersdelight = true
creeperoverhaul = true
monolib = true
betterend = true
snowrealmagic = true
another_furniture = true
crittersandcompanions = true
biomeswevegone = true
visualworkbench = true
visualoverhaul = true
skniro_furniture = true
minecraft = true
exposure = true
